development:
  adapter: postgresql
  encoding: unicode
  database: unmsocial_development
  pool: 5
  username: eddybanks
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: unmsocial_test
  pool: 5
  username: eddybanks
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: unmsocial_production
  pool: 5
  username: eddybanks
  password:
